# For local development

version: '3'

services:
  bcw-redis:
    container_name: bcw-redis
    image: redis:latest
    expose:
      - 6379
    ports:
      - '6378:6379'
    networks:
      - bc-watcher
networks:
  bc-watcher:
    name: bc-watcher
